# File: D:\Ev station\.streamlit\secrets.toml
[supabase]
URL = "https://ktglzozjiyvwifzbnemq.supabase.co"
ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0Z2x6b3pqaXl2d2lmemJuZW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMDU1MDMsImV4cCI6MjA3Njg4MTUwM30.1W54rxPtC2x-jzIqGGIPJX6DCBK4Oqnc-VzqcUirgu4"